### PR TITLE
Generate and include TypeScript types in published build

### LINKED ISSUE #8: Types not available in v.2.1.0
Hi, thanks heaps for this package! I've just updated to v2.1.0 and TypeScript isn't finding any typings for the module.

On v2.1.0 the package's typings were working perfectly (and automatically) just by installing the package. I'm guessing that's because the raw `.ts` files were installed as part of the package in v2.0.0, whereas with v2.1.0 only the transpiled JS files are included.

I don't know much about packaging TypeScript things, but I believe it should be possible to make TypeScript emit a `.d.ts` file and have that included in the npm package.

Edit: Yep, that was the solution. I've made a PR 😀

### PR DESCRIPTION
**Pull request by nathanielw**
Fixes #8

Updates the build command to output a type declaration file and points the `types` field in `package.json` to that file.

### CODE REVIEW

**Comment by xomaczar** [comment]
@pzuraq is this a viable solution? If so, can this be merged upstream and `npm publish` the new package?

**Comment by BryanCrotaz** [comment]
@pzuraq nudge

**Comment by pjcarly** [comment]
@pzuraq nudge x2

**Comment by pzuraq** [comment]
Sorry for the long wait here, this slipped through the cracks originally, thanks for the nudge!

This looks good, thanks for adding this. Will release a bugfix momentarily.

**Comment by pjcarly** [comment]
Cheers, thanks a lot

**Comment by andreyfel** [comment]
@nathanielw @pzuraq @pjcarly does it work for you guys?
I've updated the tracked-maps-and-sets to the latest but there is no index.d.ts file in node_modules.

**Comment by pjcarly** [comment]
Indeed, I think something went wrong, just noticed no index.d.ts missing

**Pull request merged**
